flightsimdiscovery/pois/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, BooleanField, HiddenField
from wtforms.validators import DataRequired, Length, ValidationError
from utilities import validate_lat, validate_long, get_country_list, get_category_list, get_new_poi_category_list
from flightsimdiscovery.pois.utils import validate_poi_name


class PoiCreateForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    country = SelectField('Country', choices=get_country_list(), render_kw={'disabled': False}, validators=[DataRequired()])
    category = SelectField('Category', choices=get_new_poi_category_list(), validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()], render_kw={'class': 'form-control', 'rows': 8})
    latitude = StringField('Latitude (decimal degrees) e.g. -34.407279', validators=[DataRequired(), Length(min=2, max=18)])
    longitude = StringField('Longitude (decimal degrees) e.g. 150.676888', validators=[DataRequired(), Length(min=2, max=18)])
    nearest_airport = StringField('Nearest Airpot (ICAO) (optional) e.g. KLAX', validators=[Length(min=0, max=4)])
    share = BooleanField('Share with the community', default="checked")
    submit = SubmitField('Create')

    def validate_latitude(self, latitude):

        if not validate_lat(str(latitude.data)):
            raise ValidationError('Please enter a valid latitude (-90 and +90) in degrees decimal.  e.g.-34.407279')

    def validate_longitude(self, longitude):

        if not validate_long(str(longitude.data)):
            raise ValidationError('Please enter a valid longitude (-180 and +180) in degrees decimal   e.g. 150.676888')

    def validate_name(self, name):

        if not validate_poi_name(name.data):
            raise ValidationError('This name is already used by another point of interest')


class PoiUpdateForm(FlaskForm):
    poi_name = HiddenField("Name")
    name = StringField('Name', validators=[DataRequired()])
    country = SelectField('Country', choices=get_country_list(), render_kw={'disabled': False}, validators=[DataRequired()])
    # country = StringField('Country', render_kw={'disabled': False})
    category = SelectField('Category', choices=get_new_poi_category_list(), validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()], render_kw={'class': 'form-control', 'rows': 8})
    latitude = StringField('Latitude (decimal degrees) ', render_kw={'disabled': False}, validators=[DataRequired(), Length(min=2, max=18)])
    # latitude = StringField('Latitude (decimal degrees) ', render_kw={'disabled': False})
    longitude = StringField('Longitude (decimal degrees)',render_kw={'disabled': False},  validators=[DataRequired(), Length(min=2, max=18)])
    altitude = StringField('altitude (meters)',render_kw={'disabled': False},  validators=[Length(min=1, max=6)])
    # longitude = StringField('Longitude (decimal degrees)',render_kw={'disabled': False})
    # nearest_airport = StringField('Nearest Airpot (ICAO) (optional)', validators=[Length(min=0, max=4)])
    share = BooleanField('Share with the community')
    submit = SubmitField('Update')

    def validate_latitude(self, latitude):

        if not validate_lat(str(latitude.data)):
            raise ValidationError('Please enter a valid latitude (-90 and +90) in degrees decimal.  e.g.-34.407279')

    def validate_longitude(self, longitude):

        if not validate_long(str(longitude.data)):
            raise ValidationError('Please enter a valid longitude (-180 and +180) in degrees decimal   e.g. 150.676888')

    def validate_altitude(self, altitude):

        try:
            float(str(altitude.data))
        except ValueError:
            raise ValidationError('Please enter a valid number to the nearest meter   e.g. 1503')

    def validate_name(self, name):

        if name.data != self.poi_name.data:
            if not validate_poi_name(name.data):
                raise ValidationError('This name is already used by another point of interest')

flightsimdiscovery/pois/routes.py
import json
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flightsimdiscovery import db
from flightsimdiscovery.pois.forms import PoiCreateForm, PoiUpdateForm
from flightsimdiscovery.models import Pois, User, Ratings, Flagged, Visited, Favorites, FP_Ratings, Flightplan, Flightplan_Waypoints
from flightsimdiscovery.pois.utils import location_exists, get_rating, validate_updated_poi_name
from flask_login import current_user, login_required
from utilities import get_country_region, continents_by_region, get_location_details
from datetime import date, datetime, timedelta

pois = Blueprint('pois', __name__)
anonymous_username = 'anonymous'


@pois.route("/poi/new", defaults={'iw_add_poi_location': None}, methods=['GET', 'POST'])
@pois.route("/poi/new/<iw_add_poi_location>", methods=['GET', 'POST'])
@login_required
def new_poi(iw_add_poi_location):
    flag_poi = False
    share_with_community = ""
    pois = Pois.query.all()
    poi_names = [poi.name for poi in pois]
    form = PoiCreateForm()
    lat = ""
    lng = ""

    country = ""
    region = ""

    # get anonymous user
    user_id = User.query.filter_by(username=anonymous_username).first().id  # returns a list 

    if current_user.is_authenticated:
        user_id = current_user.id
    else:
        # lets flag any anonymous created pois for review
        flag_poi = True
        share_with_community = 'style=display:none'   

    # populate lattiude and longitude if coming from Infowindow
    if iw_add_poi_location:
        location = iw_add_poi_location.split(", ")
        lat = location[0]
        lng = location[1]
        location_details = get_location_details(float(lat), float(lng))
        country = location_details.get('country', "")
        print('getting country details', country)
        form.latitude.data = lat
        form.longitude.data = lng
        if country:
            form.country.data = country
            form.country.render_kw = {'disabled': True}
        
        form.latitude.render_kw = {'disabled': True}
        form.longitude.render_kw = {'disabled': True}

    if form.validate_on_submit():

        # check location has not already been used by another poi
        if location_exists(pois, float(form.latitude.data), float(form.longitude.data), form.category.data):
            new_form = PoiCreateForm()
            new_form.name.data = form.name.data
            new_form.country.data = form.country.data
            new_form.description.data = form.description.data
            new_form.nearest_airport.data = form.nearest_airport.data
            new_form.share.data = form.share.data

            flash('A point of interest already exists at this location', 'danger')
            return render_template('create_poi.html', db_poi_names=poi_names, form=new_form, legend='New Poi')

        # determine country from user coordinates not from the country they input in the form
        location_details = get_location_details(float(form.latitude.data), float(form.longitude.data))
        country = location_details.get('country', "")
        if country:
            form.country.data = country

        # Update POIS table
        print('##### SHARE VALUE: ', form.share.data)
        poi = Pois(user_id=user_id, name=form.name.data, latitude=float(form.latitude.data), longitude=float(form.longitude.data),
                   region=get_country_region(form.country.data), country=form.country.data, category=form.category.data,
                   description=form.description.data,
                   nearest_icao_code=form.nearest_airport.data, share=form.share.data, flag=flag_poi)

        db.session.add(poi)
        db.session.commit()

        # Update Rating table - defaul rating when first creating a new POI is 4
        print('Poi ID is: ', poi.id)  # This gets the above poi that was just committed.
        rating = Ratings(user_id=user_id, poi_id=poi.id, rating_score=4)
        db.session.add(rating)
        db.session.commit()

        # flash('A new point of interest has been created!', 'success')
        return redirect(url_for('main.home', _anchor='google_map', pois_created='True', latitude=poi.latitude, longitude=poi.longitude, country=poi.country))

    return render_template('create_poi.html', form=form, db_poi_names=poi_names, share=share_with_community)


@pois.route("/topten_pois/<continent>")
def topten_pois(continent):
    region_pois = []
    poi_ratings = []
    topten_pois = []
    data_table = []

    # get all pois for the continent
    for region in continents_by_region[continent]:
        pois = Pois.query.filter_by(region=region).all()
        region_pois.extend(pois)

    # get poi ratings and order pois by rating hightest to lowest
    for poi in region_pois:
        rating = str(get_rating(poi.id))
        rating_dict = {'poi_id': poi.id, 'rating': rating}
        poi_ratings.append(rating_dict)

    sorted_poi_ratings = sorted(poi_ratings, key=lambda k: k['rating'])

    # get the top ten pois and  dictionary that gets posted for map to use
    for poi_dict in sorted_poi_ratings[-10:]:
        poi = Pois.query.get(poi_dict['poi_id'])

        data_dic = {}
        data_dic['id'] = poi.id
        data_dic['location'] = str(poi.latitude) + ', ' + str(poi.longitude)
        data_dic['name'] = poi.name
        data_dic['category'] = poi.category
        data_dic['country'] = poi.country
        data_dic['description'] = poi.description
        data_dic['rating'] = poi_dict['rating']

        data_table.append(data_dic)

    return render_template('topten_pois.html', pois=data_table, continent=continent)


@pois.route("/poi/<int:poi_id>/update", methods=['GET', 'POST'])
@login_required
def update_poi(poi_id):
    pois = Pois.query.all()
    poi = Pois.query.get_or_404(poi_id)
    print('current poi ID is ', poi.id)
    print(current_user.username)
    if (current_user.id not in [1,3]) and (poi.user_id != current_user.id):
        abort(403)

    form = PoiUpdateForm()

    if form.validate_on_submit():

        flash_error_msg = ''

        if not validate_updated_poi_name(pois, form.name.data, poi):
            flash_error_msg = "A point of interest already exists with the name - " + form.name.data
            
        elif location_exists(pois, float(form.latitude.data), float(form.longitude.data), form.category.data, poi):
            flash_error_msg = "A point of interest already exists at this location"

        if flash_error_msg:
            
            flash(flash_error_msg, 'danger')
            return render_template('update_poi.html', form=form)

        else:
            # determine country from user coordinates not from the country they input in the form
            location_details = get_location_details(float(form.latitude.data), float(form.longitude.data))
            country = location_details.get('country', "")
            current_time = datetime.utcnow
            if country:
                poi.country = country
            else:
                poi.country = form.country.data  # incase lookup failed fall back to user entry

            # poi.user_id = current_user.id
            poi.name = form.name.data
            poi.category = form.category.data
            poi.description = form.description.data        
            poi.latitude = form.latitude.data        
            poi.longitude = form.longitude.data  
            if form.altitude.data:      
                poi.altitude = form.altitude.data        
            poi.share = form.share.data        
            db.session.commit()

            return redirect(url_for('main.home', _anchor='google_map', pois_updated='True', latitude=poi.latitude, longitude=poi.longitude, country=poi.country))

    elif request.method == 'GET':
        form.poi_name.data = poi.name
        form.name.data = poi.name
        form.latitude.data = poi.latitude
        form.longitude.data = poi.longitude
        form.category.data = poi.category
        form.country.data = poi.country
        form.altitude.data = poi.altitude
        form.description.data = poi.description
        # form.nearest_airport.data = poi.nearest_icao_code
        form.share.data = poi.share

    return render_template('update_poi.html', form=form)


@pois.route("/poi/<int:poi_id>/delete", methods=['POST'])
@login_required
def delete_poi(poi_id):
    
    # *** WHEN WE DELETE A POI, WE HAVE DELETE THE CORRESPONDING POI OUT OF THE OTHER TABLES  ****

    category = request.args.get('page')
    poi = Pois.query.get_or_404(poi_id)
    flagged_poi = Flagged.query.filter_by(poi_id=poi_id).first()

    # visited and favorite can contain multuple records for the one poi_id
    visited_poi_list = Visited.query.filter_by(poi_id=poi_id).all()
    favorited_pois_list = Favorites.query.filter_by(poi_id=poi_id).all()
    ratings_poi_list = Ratings.query.filter_by(poi_id=poi_id).all()

    if (current_user.id not in [1,3]) and (poi.user_id != current_user.id):
        abort(403)

    db.session.delete(poi)
    if flagged_poi:
        db.session.delete(flagged_poi)

    for visited_poi in visited_poi_list:
        db.session.delete(visited_poi)
    for favorited_pois in favorited_pois_list:
        db.session.delete(favorited_pois)
    for ratings_poi in ratings_poi_list:
        db.session.delete(ratings_poi)

    # delete record from flight plan tables that contain poi
    fp_id_set = set()
    fp_waypoints_poi_list = Flightplan_Waypoints.query.filter_by(poi_id=poi_id).all()

    for fp_waypoints_poi in fp_waypoints_poi_list:
        fp_id_set.add(fp_waypoints_poi.flightplan_id)

    for fp_id in fp_id_set:
        fp = Flightplan.query.filter_by(id=fp_id).first()
        db.session.delete(fp)

        fp_rating = FP_Ratings.query.filter_by(flightplan_id=fp_id).first()
        db.session.delete(fp_rating)

        fp_waypoints = Flightplan_Waypoints.query.filter_by(flightplan_id=fp_id).all()

flightsimdiscovery/templates/account.html
{% extends "base.html" %}
{% block content %}
<!-- bradcam_area  -->
<div class="bradcam_area register_bg">
    <div class="container">
        <div class="row">
            <!-- <div class="col-xl-12">
                <div class="bradcam_text text-center">
                    <h3>Account</h3>
                    <p>{{ current_user.username }}</p>
                </div>
            </div> -->
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<div class="container">
    <div class="account_section">
        <!-- <div class="media mt-5">
          <img class="rounded-circle  align-self-center mr-4 " src="{{ image_file }}">
          <div class="media-body">
            <h3 class="account-heading mt-3">{{ current_user.username }}</h3>
            <p class="text-secondary">{{ current_user.email }}</p>
            <p class="text-secondary">User ID is {{ current_user.id }}</p>
          </div>
        </div> -->
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group mt-5">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.goto_map_home_page(class="form-check-input") }}
                    {{ form.goto_map_home_page.label(class="form-check-label") }}
                </div>
                <!-- <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div> -->
            </fieldset>
            <div class="form-group mb-5">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
</div>
<script src="https://code.jquery.com/jquery.min.js"></script>
<script type="text/javascript">
    $(document).on("click", ".open_delete_modal", function () {
       
       var eventId = $(this).data('id');
       var form_action = '/poi/' + eventId + '/delete'
       console.log(form_action)
       $("#delete_poi_confirm").attr('action', form_action);
       console.log(eventId);
       $('#poi').html( eventId );
  });

</script>
{% endblock content %}

flightsimdiscovery/templates/all_pois.html
{% extends "base.html" %}
{% block content %}

<div class="mx-5">
    <div class="user_pois_section my-5">
        <div class="db_table_area">
            <legend class="border-bottom mb-5">All Points of Interest</legend>
            <table id="all_pois_datatable" class="stripe row-border">
                <thead class="">
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">ID</th>
                    <th scope="col">User</th>
                    <th scope="col">Name</th>
                    <th scope="col">Category</th>
                    <th scope="col">Country</th>
                    <th scope="col">Description</th>
                    <th scope="col">Map</th>
                    <th scope="col">Update</th>
                    <th scope="col">Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for poi in all_pois %}
                <tr>
                    
                    <td>{{poi.date_posted}}</td>
                    <td>{{poi.id}}</td>
                    <td>{{poi.username}}</td>
                    <td>{{poi.name}}</td>
                    <td>{{poi.category}}</td>
                    <td>{{poi.country}}</td>

                    <td>{{poi.description}}</td>
                    <td><a href="/focus_on_poi/{{poi.location}}#searchTag" class="btn btn-primary" onclick="this.form.submit()" role="button"
                           aria-disabled="true"><i class="fas fa-globe-americas"></i></a></td>
                    <!-- <td><a href="/poi/{{poi.id}}/update">update</a></td> -->
                    <td><a href="/poi/{{poi.id}}/update" class="btn btn-info" role="button" aria-disabled="true"><i
                            class="fas fa-edit"></i></a></td>
                    <!-- <td><button type="button" class="btn btn-info" data-id="{{poi.id}}" data-toggle="modal" data-target="#deleteModal"><i class="fas fa-edit"></i></button></td> -->
                    <td>
                        <button type="button" class="open_delete_modal btn btn-danger" data-id="{{poi.id}}"
                                data-toggle="modal" data-target="#deleteModal"><i class="far fa-trash-alt"></i></button>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Delete Modal -->
<div class="custom_search_pop">
    <div
            class="modal fade"
            id="deleteModal"
            tabindex="-1"
            role="dialog"
            aria-labelledby="deleteModalLabel"
            aria-hidden="true"
    >
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">
                        Are you sure you want to delete this point of interest?
                    </h5>
                    <input type="hidden" name="eventId" id="eventId"/>
                    <!-- <span id="poi"></span> -->
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        Close
                    </button>
                    <!-- <form action="{{ url_for('pois.delete_poi', poi_id=2) }}" method="POST"> -->
                    <form id="delete_poi_confirm" action="" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery.min.js"></script>
<script type="text/javascript">
    $(document).on("click", ".open_delete_modal", function () {
       
       var eventId = $(this).data('id');
       var form_action = '/poi/' + eventId + '/delete'
       console.log(form_action)
       $("#delete_poi_confirm").attr('action', form_action);
       console.log(eventId);
       $('#poi').html( eventId );
  });

  

</script>
{% endblock content %}

flightsimdiscovery/templates/contact.html
{% extends "base.html" %}
{% block content %}
<!-- bradcam_area  -->
<div class="bradcam_area contact_us_bg">
    <div class="container">
        <!-- <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text text-center">
                    <h3>Contact Us</h3>
                    <p>Search - Download - Explore</p>
                </div>
            </div> -->
    </div>
</div>
<!--/ bradcam_area  -->

<!-- ================ contact section start ================= -->
<div class="about_story">
    <div class="container">
        <div class="row my-5">
            <div class="col-12">
                <h3 class="contact-title">Get in Touch</h3>
            </div>
            <!-- <div class="col-lg-8">
                <form class="form-contact contact_form" action="" method="post" id="contactForm"
                      novalidate="novalidate">
                    {{ form.hidden_tag() }}
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                {{ form.message.label(class="form-control-label") }}
                                {% if form.message.errors %}
                                {{ form.message(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.message.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.message(class="form-control form-control-lg", cols="30", rows="9") }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                {{ form.subject.label(class="form-control-label") }}
                                {% if form.subject.errors %}
                                {{ form.subject(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.subject.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.subject(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                {{ form.email.label(class="form-control-label") }}
                                {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="form-group mt-3">
\
                        {{ form.submit(class="button button-contactForm boxed-btn") }}
                    </div>
                </form>
            </div> -->
            <!-- <div class="col-lg-3 offset-lg-1 mt-4"> -->
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-email"></i></span>
                    <div class="media-body">
                        <h3>flightsimdiscovery@gmail.com</h3>
                        <p>Send us your query anytime!</p>
                    </div>
                </div>
            <!-- </div> -->
        </div>
    </div>
 <div>
    <!-- ================ contact section end ================= -->
{% endblock content %}

flightsimdiscovery/templates/flagged_pois.html
{% extends "base.html" %}
{% block content %}

<div class="mx-5">
    <div class="user_pois_section my-5">
        <div class="db_table_area">
            <legend class="border-bottom mb-5">Flagged Points of Interest</legend>
            <table id="flagged_pois_datatable" class="stripe row-border">
                <thead class="">
                <tr>
                    <th scope="col">User</th>
                    <th scope="col">POI ID</th>
                    <th scope="col">POI Name</th>
                    <th scope="col">Flagged Date</th>
                    <th scope="col">Reason</th>              
                    <th scope="col">Map</th>              
                    <th scope="col">Remove Flag</th>
                    <th scope="col">Update</th>
                    <th scope="col">Delete</th>

                </tr>
                </thead>
                <tbody>
                {% for flagged_poi_data in flagged_pois_data %}
                <tr>
                    <td>{{flagged_poi_data.username}}</td>
                    <td>{{flagged_poi_data.poi_id}}</td>
                    <td>{{flagged_poi_data.name}}</td>
                    <td>{{flagged_poi_data.date_posted}}</td>
                    <td>{{flagged_poi_data.reason}}</td>
                    <td><a href="/focus_on_poi/{{flagged_poi_data.location}}#searchTag" class="btn btn-primary" onclick="this.form.submit()" role="button"
                        aria-disabled="true"><i class="fas fa-globe-americas"></i></a></td>
                    <td>
                        <a style="cursor:pointer" href="/poi/delete_flagged_poi/{{flagged_poi_data.poi_id}}?page=flagged_pois">
                            <i class="fas fa-minus-circle fa-2x" title='remove flag' style="color:#f3d10d;"></i></button>
                    </td>
                    <td><a href="/poi/{{flagged_poi_data.poi_id}}/update" class="btn btn-info" role="button" aria-disabled="true"><i
                        class="fas fa-edit"></i></a>
                    </td>
                    <td>
                        <button type="button" class="open_delete_modal btn btn-danger" data-id="{{flagged_poi_data.poi_id}}"
                                data-toggle="modal" data-target="#deleteModal"><i class="far fa-trash-alt"></i></button>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Delete Modal -->
<div class="custom_search_pop">
    <div
            class="modal fade"
            id="deleteModal"
            tabindex="-1"
            role="dialog"
            aria-labelledby="deleteModalLabel"
            aria-hidden="true"
    >
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">
                        Are you sure you want to delete this point of interest?
                    </h5>
                    <input type="hidden" name="eventId" id="eventId"/>
                    <!-- <span id="poi"></span> -->
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        Close
                    </button>
                    <!-- <form action="{{ url_for('pois.delete_poi', poi_id=2) }}" method="POST"> -->
                    <form id="delete_poi_confirm" action="" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery.min.js"></script>
<script type="text/javascript">
    $(document).on("click", ".open_delete_modal", function () {
       
       var poi_id = $(this).data('id');
       var form_action = '/poi/' + poi_id + '/delete'
       $("#delete_poi_confirm").attr('action', form_action);
  });


  $('#remove_poi_flag_btn').click(function(){
       
       var poi_id = $(this).data('id');
       var form_action = '/delete_flagged_poi/' + poi_id
       $("#delete_poi_confirm").attr('action', form_action);
       console.log(eventId);
       $('#poi').html( eventId );
  });
  

</script>
{% endblock content %}